### ISSUE TITLE
TODO by first boss

### ISSUE THREAD

**Issue by Ryguy-9999** [elliegoldstein/hellevator#1]
- [ ] Enemies move back and stun on hit
- [ ] Easier code to kill player (for boom spider)
- [ ] Right click cooldown
- [ ] Combat roll cooldown
- [ ] Adjust damage, health, repair...
- [ ] Buffer spider
- [ ] Create and tune functional and fixed spawn
- [ ] Enemies redirect when player dies
- [ ] Boss
