### ISSUE TITLE
 Boss

### ISSUE THREAD

**Issue by elliegoldstein** [elliegoldstein/hellevator#25]
**Phase 1 (Hanging from the web):**
- [x] Knock legs out of gears to resume elevator (repeat 3 times)
- [x] Between leg removing, boss goes all out on attacks until it blocks gears again
- [x] At start of 3rd round, spawn Buffer spider
- [ ] Attack cycle:
    - [x] Stab with each free leg
    - [ ] Spit row of webs
    - [ ] Drop eggs by free gears
    - [ ] All legs stab to create a short range ring of bullets

**Phase 2 (On the elevator):**
- [ ] Just a circle that bounces around, gaining momentum when shot
- [ ] Will skew bounces toward player
- [ ] Toward end, will curve toward player
- [ ] Occasionally fire spray, amount depending on momentum, will direct momentum away from player
